apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server
  template:
    metadata:
      labels:
        app: media-server
    spec:
      containers:
      - name: server
        image: thequy/media-server:v1.0.0
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: media-config
              key: media-server-port
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: media-config
              key: rabbitmq-host
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: media-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: media-config
              key: redis-port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: media-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: media-secrets
              key: rabbitmq-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: media-secrets
              key: redis-password
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: media-server-service
spec:
  selector:
    app: media-server
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer