apiVersion: v1
kind: Secret
metadata:
  name: media-secrets
type: Opaque
data:
  rabbitmq-username: bXl1c2Vy  # Base64 encoded 'myuser'
  rabbitmq-password: bXlwYXNzd29yZA==  # Base64 encoded 'mypassword'
  redis-password: bXlyZWRpc3Bhc3N3b3Jk  # Base64 encoded 'myredispassword'